const createEntity = require('brain/createEntity'); 

const clothes = createEntity('clothes')
	.entries({
		"balaclava": ["balaclava"],
		"bathing suit": ["bathing suit"],
		"beanie": ["beanie"],
		"boots": ["boots"],
		"bra": ["bra"],
		"capri": ["capri"],
		"cardigan": ["cardigan"],
		"casual shirt": ["casual shirt"],
		"coat": ["coat"],
		"dress pants": ["dress pants"],
		"dress shirt": ["dress shirt"],
		"dress": ["dress"],
		"fleece top": ["fleece top"],
		"flips flops": ["flips flops"],
		"gloves": ["gloves"],
		"gum boots": ["gum boots","gumboots"],
		"hat": ["hat"],
		"hoodie": ["hoodie"],
		"jacket": ["jacket"],
		"jeans": ["jeans"],
		"jumper": ["jumper"],
		"khakis": ["khakis"],
		"lounge wear": ["lounge wear"],
		"neck gaiter": ["neck gaiter"],
		"pajama": ["pajama","pyjama"],
		"pants": ["pants"],
		"pool shoes": ["pool shoes"],
		"rain coat": ["rain coat","raincoat"],
		"rain jacket": ["rain jacket"],
		"rain pants": ["rain pants"],
		"sandals": ["sandals"],
		"scarf": ["scarf"],
		"shawls": ["shawls"],
		"shorts": ["shorts"],
		"ski pants": ["ski pants"],
		"skirt": ["skirt","skirts"],
		"sleepwear": ["sleepwear"],
		"sleeve shirt":["sleeve shirt"],
		"slippers": ["slippers"],
		"sneakers": ["sneakers"],
		"snowboard pants": ["snowboard pants"],
		"socks": ["socks"],
		"suit": ["suit"],
		"sunglasses": ["sunglasses","sun glasses"],
		"sunscreen": ["sunscreen"],
		"sweater": ["sweater"],
		"sweatpants": ["sweatpants"],
		"sweatshirt": ["sweatshirt"],
		"swim goggles": ["swim goggles"],
		"swimwear": ["swimwear"],
		"t-shirt": ["t-shirt"],
		"tank top": ["tank top"],
		"tennis shoes": ["tennis shoes"],
		"thermal pants": ["thermal pants"],
		"tie": ["tie"],
		"turtleneck": ["turtleneck"],
		"umbrella": ["umbrella"],
		"underwear": ["underwear"],
		"wool cap": ["wool cap"],
		"wool socks": ["wool socks","woolen socks"]
	});

module.exports = clothes;